# 使用Scikit-learn實作人工類神經網路(ANN)

## 介紹

##  Cite Scikit-learn: Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011.

Class  <font size="3" color="red">MLPClassifier</font> implements a multi-layer perceptron (MLP 多層感知器) algorithm that trains using Backpropagation.

MLP trains on two arrays: array X of size (n_samples, n_features), which holds the training samples represented as floating point feature vectors; and array y of size (n_samples), which holds the target values (class labels) for the training samples:

## IMPORT
<font size="3" color="red">from sklearn.neural_network import MLPClassifier</font>  (Note: for contimuous number using MLPRegressor) 
## CLASS
```C
MLPClassifier(hidden_layer_sizes=(100, ), 
              activation='relu', 
              solver='adam', 
              alpha=0.0001, 
              batch_size='auto', 
              learning_rate='constant', 
              learning_rate_init=0.001, 
              power_t=0.5, 
              max_iter=200, 
              shuffle=True, 
              random_state=None, 
              tol=0.0001, 
              verbose=False, 
              warm_start=False, 
              momentum=0.9, 
              nesterovs_momentum=True, 
              early_stopping=False, 
              validation_fraction=0.1, 
              beta_1=0.9, 
              beta_2=0.999, 
              epsilon=1e-08)
```              
```C              
參數說明

hidden_layer_sizes=(100, 2)  # 隱藏層的數量, 此範例是第一隱藏層有100個nodes(神經元)，第二隱藏層有2個nodes(神經元)
default 100


activation='relu'  # 激勵函數
default relu {identity, logistic, tanh, relu}

# identity, no-op activation, useful to implement linear bottleneck, returns f(x) = x
# logistic, the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).
# tanh, the hyperbolic tan function, returns f(x) = tanh(x).
# relu, the rectified linear unit function, returns f(x) = max(0, x)

solver='adam' #  The solver for weight optimization(使 LOSS最小之最佳化方式).
default adam {lbfgs, adam, sgd}

# 'lbfgs' is an optimizer in the family of quasi-Newton methods (good for robot data).
# 'sgd' refers to stochastic gradient descent(隨機梯度下降法).
# 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba(隨機梯度下降優化技術)
# 建議小型的資料集使用L-BFGS (要計算Hessian逆矩阵)
# 資料集	方式
#  小樣本集使用 lbfgs (收斂較快、效果較好)
#  大樣本集(超過數千個樣本) 使用adam/sgd (效果較好)

alpha = 1e-05  #L2 penalty (regularization term) parameter( L2正規化參數，可降低過擬合的風險)
default 0.0001

batch_size  # Size of minibatches for stochastic optimizers
default auto(200, n_samples)
#如果solver是lbfgs，則不考慮
    
learning_rate='constant' #Learning rate schedule for weight updates (學習速率參數變化方式)
default constant {constant, invscaling, adaptive}
# Only used when solver='sgd'. 只有使用'sgd'or'adam'才會使用的學習速率參數權重係數更新
# constant:依learning_rate_init之設定，不改變學習速率
# invscaling:逐漸減小，effective_learning_rate = learning_rate_init / pow(t, power_t)
# adaptive:只要Cost function保持下降，那學習速率就會保持不變。但是當不能有效降低或當early_stopping=on，不能增加驗證分數的時候，那學習速率就會調整(目前學習速率除以5)
    
learning_rate_init==0.001 #學習速率參數
default 0.001
# Only used when solver='sgd' or 'adam'.

power_t=0.5  #反縮放學習效率的指數，當learning_rate=invscaling時用來更新有效的學習速率。
default 0.5
# Only used when solver='sgd'.

max_iter=200  #最大迭代次數，看是先到tol還是先到max_iter。
default 200


shuffle #每次的迭次是否要對樣本進行亂數洗牌。
default True {True, False}
#Only used when solver='sgd' or 'adam'.

random_state=1 #隨機數生成器的狀態或種子
default None

tol  #Tolerance for the optimization.優化的容忍度，假如連續兩次的迭代無法降低成本函數，或是得分無法增加，除非learning_rate='adaptive'，不然就當做已經收斂完成而結束。
default 0.0001

verbose=0  #是否將過程輸出至stdout，預設不輸出過程
default 0
# 0 不輸出
# 1 偶爾輸出
# 2 一定輸出

warm_start 如果想用之前解決方法做為初始擬合，使用更多監控方式進行模型的控制，可以使用for流程配合使用，否則釋放之前的解決方法。
default False {True, False}

momentum  # Momentum for gradient descent update. 配合sgd的一個動量梯度下降更新的設置參數，(0-1)
default 0.9
#Only used when solver='sgd'

nesterovs_momentum #nesterovs_momentum是momentum的一個改良(Nesterov's momentum技術)。
default True {True, False}
#Only used when solver='sgd' 與 momentum>0

early_stopping
default False {True, False}
# 設置用於當驗證得分沒有改善的時候是否要提早結束。
# 如果設置True的話，則會自動拿10%數據集來做驗證，當最後兩次的迭代都沒有改善的時候就會停止(低於tol優化容忍度)。
# Only effective when solver='sgd' or 'adam'

validation_fraction  # 早期停止驗證的預留訓練數據集的比例，early_stopping=True的時候有效。
default 0.1

beta_1
default 0.9(0-1)
# Only used when solver='adam' 估計一階矩陣向量的指數衰減速率

beta_2
default 0.999(0-1)
# Only used when solver='adam'估計二階矩陣向量的指數衰減速率

epsilon
default 1e-8
# Only used when solver='adam' 數據穩定植
```

## 簡單的範例

In [7]:
from sklearn.neural_network import MLPClassifier

In [8]:
X = [[0., 0.], [1., 1.]]
y = [0, 1]

In [9]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)

In [10]:
clf.fit(X, y)

,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(5, ...)"
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'lbfgs'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",1e-05
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",200
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary `.",1


In [11]:
clf.predict([[2., 2.], [-2.,-2.]])

array([1, 0])

In [12]:
clf.predict([[-2, -2.], [2.,2.]] )

array([0, 1])

MLP can fit a non-linear model to the training data. clf.coefs_ contains the weight matrices that constitute the model parameters:

In [13]:
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 2), (2, 1)]

In [14]:
clf.coefs_[0]

array([[-0.14196276, -0.02104562, -0.85522848, -3.51355396, -0.60434709],
       [-0.69744683, -0.9347486 , -0.26422217, -3.35199017,  0.06640954]])

In [15]:
clf.coefs_[1]

array([[ 0.29164405, -0.14147894],
       [ 2.39665167, -0.6152434 ],
       [-0.51650256,  0.51452834],
       [ 4.0186541 , -0.31920293],
       [ 0.32903482,  0.64394475]])

In [16]:
clf.coefs_[2]

array([[-4.53025854],
       [-0.86285329]])

In [17]:
clf.predict_proba([[2., 2.], [-2., -2.]]) 

array([[1.96718015e-004, 9.99803282e-001],
       [1.00000000e+000, 2.80288501e-171]])

MLPClassifier supports multi-class classification by applying Softmax as the output function.
![My photo](softmax_formula.png)  
Further, the model supports multi-label classification in which a sample can belong to more than one class. For each class, the raw output passes through the logistic function. Values larger or equal to 0.5 are rounded to 1, otherwise to 0. For a predicted output of a sample, the indices where the value is 1 represents the assigned classes of that sample:

In [18]:
X = [[0., 0.], [1., 1.]]
y = [[0, 1], [1, 1]]  ## multi-label classification
clf = MLPClassifier(solver='lbfgs', 
                    hidden_layer_sizes=(15, ), 
                    random_state=1)   

In [19]:
clf.fit(X, y)

,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(15,)"
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'lbfgs'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",200
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary `.",1


In [20]:
[coef.shape for coef in clf.coefs_]

[(2, 15), (15, 2)]

In [21]:
clf.coefs_[0]

array([[-0.02928603, -0.06963557, -0.84184392, -0.06976421, -1.12407119,
        -0.14387892, -0.60254253, -0.05450738, -0.03643461,  0.41993631,
         1.79193816,  0.10613166, -0.10430983, -0.17237806, -0.16680255],
       [ 0.06016434, -0.17658253, -0.6447018 , -0.12692086, -1.10594942,
         0.10614398, -0.32654508, -0.06584957,  0.06787783,  0.53907821,
         1.95972884, -0.10569259, -0.16268476, -0.42235897,  0.1334606 ]])

In [22]:
clf.coefs_[1]

array([[-0.01839032,  0.1442086 ],
       [-0.04812967, -0.05813919],
       [-1.85093806,  0.30396526],
       [ 0.05702603, -0.09158103],
       [-1.75169949,  0.40767026],
       [-0.15763502,  0.02615887],
       [-1.0138012 ,  0.44593929],
       [-0.23304839,  0.05651332],
       [-0.03033285,  0.06861107],
       [ 0.7083076 ,  0.19755353],
       [ 2.92289555,  1.1870438 ],
       [-0.15305213,  0.8550227 ],
       [ 0.0305485 ,  0.14237558],
       [-0.86434499,  0.21626088],
       [ 0.10848985, -0.03611366]])

In [23]:
clf.predict([[1., 1.]])

array([[1, 1]])

In [24]:
clf.predict([[0., 0.]])

array([[0, 1]])

## 使用ANN預測股市漲跌
讀入上一次處理好的股市漲跌資料來進行預測

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
market = pd.read_csv('market.csv')
market.head()

,Date,^TWII,^AORD,^AXJO,^BFX,^BSESN,^BUK100P,^BVSP,^DJI,^FCHI,...,^MXX,^N225,^NYA,^NZ50,^RUT,^STOXX50E,^TA125.TA,^XAX,000001.SS,IMOEX.ME
0,2015-04-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
1,2015-04-27,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,2015-04-29,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2015-05-06,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,2015-05-11,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0


In [27]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(
    market.iloc[:, 2:], market['^TWII'], 
    train_size=0.8, 
    random_state=1)

In [28]:
mlp = MLPClassifier(hidden_layer_sizes=(50,), max_iter=20, alpha=1e-4,
                    solver='sgd', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

mlp.fit(train_x, train_y)
print("Training set score: %f" % mlp.score(train_x, train_y))
print("Test set score: %f" % mlp.score(test_x, test_y))

Iteration 1, loss = 0.67819994
Iteration 2, loss = 0.66690368
Iteration 3, loss = 0.65170263
Iteration 4, loss = 0.63698058
Iteration 5, loss = 0.61959334
Iteration 6, loss = 0.60526840
Iteration 7, loss = 0.59336309
Iteration 8, loss = 0.58504754
Iteration 9, loss = 0.57799943
Iteration 10, loss = 0.57284179
Iteration 11, loss = 0.56872590
Iteration 12, loss = 0.56472188
Iteration 13, loss = 0.56818511
Iteration 14, loss = 0.55847016
Iteration 15, loss = 0.55556555
Iteration 16, loss = 0.55986945
Iteration 17, loss = 0.55402597
Iteration 18, loss = 0.54808346
Iteration 19, loss = 0.54577976
Iteration 20, loss = 0.54305632
Training set score: 0.736041
Test set score: 0.636364


/home/yfhd/Documents/114-2/Data Science/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


## 改變感知機數量提高預測分數

In [29]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100, 100, 100), 
                    max_iter=100000000,
                    alpha=1e-4,
                    solver='sgd', 
                    tol=1e-4, 
                    random_state=1,
                    learning_rate_init=.1)

mlp.fit(train_x, train_y)
mlp.score(test_x, test_y)

0.6565656565656566

In [30]:
mlp = MLPClassifier(hidden_layer_sizes=(1000, 500, 500, 500, 500), 
                    max_iter=100000000,
                    alpha=1e-4,
                    solver='sgd', 
                    tol=1e-4, 
                    random_state=1,
                    learning_rate_init=.1)

mlp.fit(train_x, train_y)
mlp.score(test_x, test_y)

0.6767676767676768

In [31]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 300, 300, 100, 300, 500), 
                    max_iter=100000000,
                    alpha=1e-4,
                    solver='sgd', 
                    tol=1e-4, 
                    random_state=1,
                    learning_rate_init=.1)

mlp.fit(train_x, train_y)
mlp.score(test_x, test_y)

0.7171717171717171

## 請嘗試改變 hidden layer, node number, learning rate, normalization, or changing activaton function to improve your ANN models.